apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightdeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      name: flightpod
      labels:
        app: flight
    spec:
      containers:
      - name: flightcont
        image: image_name
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flightsvc
spec:
  type: NodePort
  selector:
    app: flight
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
...
