apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightdeployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: flight
  template:
    metadata:
      name: flightpod
      labels:
        app: flight
    spec:
      containers:
      - name: flightcont
        image: siddhardan/flight25823
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flightsvc
spec:
  type: ClusterIP
  selector:
    app: flight
  ports:
  - port: 80
    targetPort: 8080
...