---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flightdeployment
  labels:
    app: flight
    tier: app-server
    env: prod 
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: flight
      env: prod
  template:
    metadata:
      name: flightpod
      labels:
        app: flight
        env: prod
    spec:
      containers:
      - name: flightcont
        image: image_name
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: flightsvc
spec:
  type: NodePort
  selector:
    app: flight
    env: prod
  ports:
  - port: 80
    targetPort: 8080
    nodePort: 30000
<<<<<<< HEAD
...
=======
...
>>>>>>> ca0f008afed05fa70a88a6278632b8793db2d84b
